config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create

  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  # strong params
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_card.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://loremflickr.com/320/200/restaurant,<%= restaurant.category.downcase %>/all?lock=<%= restaurant.id %>);">
  <%= link_to restaurant.name, restaurant_path(restaurant), class: 'text-decoration-none text-white' %>
</div>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address, input_html: { class: 'thisishowtoaddacustomclass'} %>
  <%= f.input :rating %>
  <%= f.submit 'Submit', class: 'btn btn-primary mt-2' %>
<% end %>

app/views/restaurants/_side_info.html.erb
<p class="fw-lighter opacity-75">
  <i class="fas fa-map-pin"></i><span class='ms-2'><%= @restaurant.address %></span>
</p>
<p class="fw-lighter opacity-75">
  <% rand(2..5).times do %>
    <i class="fas fa-dollar-sign"></i>
  <% end %>
</p>
<p class="fw-lighter opacity-75">
  <i class="fas fa-utensils"></i><span class='ms-2'><%= @restaurant.category %></span>
</p>
<div class="d-flex">
  <!-- edit and delete here-->
  <p>
    <%#= link_to edit_restaurant_path(@restaurant), class: 'text-dark text-decoration-none' do %>
      <%# <i class="fas fa-pencil-alt mx-1"></i> %>
      <%# end %>
      <%= link_to restaurant_path(@restaurant), class: 'text-dark text-decoration-none', data: { turbo_method: :delete, turbo_confirm: "Do you want to delete #{@restaurant.name}" } do %>
        <i class="fas fa-trash mx-1"></i>
      <% end %>
    </p>
  </div>

app/views/restaurants/index.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Restaurants</h1>
    <%= link_to new_restaurant_path, class: 'text-dark text-decoration-none' do %>
      <i class="fa-solid fa-plus"></i>
    <% end %>
  </div>
  <div class="cards">
    <% @restaurants.each do |restaurant| %>
      <%= render 'restaurants/card', restaurant: restaurant %>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>Add Restaurant</h1>
  <%= render 'restaurants/form' %>
</div>

app/views/restaurants/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://loremflickr.com/320/200/restaurant,<%= @restaurant.category.downcase %>/all?lock=<%= @restaurant.id %>);">
  <div class="container">
  </div>
</div>
<div class="container mt-2">
  <div class="row justify-content-around">
    <div class="col-12 col-sm-8" data-controller="insert-review">
      <p>
        <%= link_to '< Restaurants', restaurants_path, class: 'btn-light opacity-25 text-decoration-none' %>
      </p>
      <div class="d-flex align-items-center">
        <h1 class="m-0"><%= @restaurant.name %></h1>
        <p class="m-0 ms-2" style="font-size: 0.8em">
          <% @restaurant.id.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% (5 - @restaurant.id).times do %>
            <i class="far fa-star"></i>
          <% end %>
        </p>
      </div>
      <p class="fw-lighter opacity-75 mt-2"><%= Faker::Restaurant.description  %></p>
      <h3>
        Reviews
        <%= link_to '+', new_restaurant_review_path(@restaurant)  %>
      </h3>
      <ul>
        <% if @restaurant.reviews.any? %>
          <% @restaurant.reviews.each do |review| %>
            <li>
              <%= review.content %>
              <%= link_to 'x', review_path(review), data: { turbo_method: :delete, turbo_confirm: 'Delete review?' } %>
            </li>
          <% end %>
        <% else %>
          <li>No reviews yet</li>
        <% end %>
      </ul>
    </div>
    <div class="col-12 col-sm-4 mt-5">
      <%= render 'restaurants/side_info' %>
    </p>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Add a Review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content, input_html: { class: 'thisishowtoaddacustomclass'} %>
    <%= f.submit class: 'btn btn-info mt-2' %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to restaurants_path, class: "navbar-brand" do %>
      <i class="fas fa-utensils"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%#= link_to "Top Restaurants", top_restaurants_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= image_tag "https://content.imageresizer.com/images/memes/Hey-can-I-copy-your-homework-Template-meme-7.jpg", class: "avatar" %>
        </li>
      </ul>
    </div>
  </div>
</div>